steps:
  # 1. Sending info to Slack
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        if [ $PROJECT_ID == 'coinpanel-dev' ]; then 
          gcloud pubsub topics publish cloud-builds-custom --message '{"build": "$BUILD_ID", "branch": "$BRANCH_NAME", "repo": "$REPO_NAME"}' ; 
        fi
  - name: 'ubuntu'
    args: ['mv', '.env-${_CLUSTER_TYPE}', '.env']
  #- name: 'ubuntu'
  #  args: ['mv', 'public/maintainence.html', 'public/index.html']
  - name: node:12.10.0
    entrypoint: yarn
    args: ['install']
  - name: node:12.10.0
    entrypoint: yarn
    args: ['run', 'build']
  - name: gcr.io/project-id/firebase
    args: [ 'deploy', '--project=coinpanel-${_CLUSTER_TYPE}',]
substitutions:
  _CLUSTER_TYPE: ${PROJECT_ID:10}
timeout: 1200s
options:
  dynamic_substitutions: true

