steps:
  - name: 'ubuntu'
    args: ['mv', '.env-${_CLUSTER_TYPE}', '.env']
  #- name: 'ubuntu'
  #  id: prepare
  #  args: ['sh', 'deployment-helper/preplacer_pr.sh', '${_IMAGE_NAME}']
  - name: node:12.10.0
    entrypoint: yarn
    args: ['install']
  - name: node:12.10.0
    entrypoint: yarn
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cp-web-server-${_IMAGE_NAME}:$SHORT_SHA", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cp-web-server-${_IMAGE_NAME}:$SHORT_SHA"]
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Setup
    args: ['container', 'clusters', 'get-credentials', 'cp-${_CLUSTER_TYPE}-cluster-eu', '--region=europe-north1', '--project=$PROJECT_ID']
  - name: 'ubuntu'
    id: preDeploy
    #dir: 'server'
    args: ['sh', 'deployment-helper/replacer_pr.sh', '$SHORT_SHA', '$PROJECT_ID', '${_IMAGE_NAME}']
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    #dir: 'server'
    args:
      - 'apply'
      - '-f'
      - 'deployment_pr.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-north1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cp-${_CLUSTER_TYPE}-cluster-eu'
substitutions:
  _CLUSTER_TYPE: ${PROJECT_ID:10}
  _IMAGE_NAME_MIXCASE: ${BRANCH_NAME//\//-}
  _IMAGE_NAME_NONDERSCORE: ${_IMAGE_NAME_MIXCASE//_/-}
  _IMAGE_NAME: ${_IMAGE_NAME_NONDERSCORE,,}
timeout: 1200s
options:
  dynamic_substitutions: true

