steps:
  - name: node:12.10.0
    entrypoint: yarn
    args: ['install']
  - name: node:12.10.0
    entrypoint: yarn
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cp-web-server:$SHORT_SHA", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cp-web-server:$SHORT_SHA"]
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Setup
    args: ['container', 'clusters', 'get-credentials', 'cp-dev-cluster', '--region=asia-northeast1', '--project=$PROJECT_ID']
  - name: 'ubuntu'
    id: preDeploy
    #dir: 'server'
    args: ['sh', 'deployment-helper/replacer.sh', '$SHORT_SHA', '$PROJECT_ID']
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    #dir: 'server'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast1'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cp-dev-cluster'
