steps:
  - name: node:12.10.0
    entrypoint: yarn
    args: ['install']
  - name: node:12.10.0
    entrypoint: yarn
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cp-web-server:$SHORT_SHA", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cp-web-server:$SHORT_SHA"]
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Setup
    args: ['container', 'clusters', 'get-credentials', 'cp-${_CLUSTER_TYPE}-cluster-eu', '--region=europe-north1', '--project=$PROJECT_ID']
  - name: 'ubuntu'
    id: preDeploy
    #dir: 'server'
    args: ['sh', 'deployment-helper/replacer.sh', '$SHORT_SHA', '$PROJECT_ID']
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    #dir: 'server'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-north1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cp-${_CLUSTER_TYPE}-cluster-eu'
substitutions:
  _CLUSTER_TYPE: ${PROJECT_ID:10}
options:
  dynamic_substitutions: true

