apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: gcr.io/<GCP_PROJECT>/cp-web-server:<IMAGE_VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 100Mi
        ports:
        - containerPort: 5000
