apiVersion: v1
kind: Service
metadata:
  name: web-server-lb
  namespace: marketdata
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  namespace: marketdata
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      nodeSelector: 
        cloud.google.com/gke-nodepool: market-data-pool
      containers:
      - name: web-server
        image: gcr.io/<GCP_PROJECT>/cp-web-server:<IMAGE_VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 100Mi
        ports:
        - containerPort: 5000
