import {
  updateSymbols,
  updateSymbolDetails,
  updateSelectedSymbol,
  updateSelectedSymbolDetail,
  updateSelectedSymbolBalance,
  updateSelectedBaseSymbolBalance,
  updateIsLoadingBalance,
  updateSelectedSymbolLastPrice,
  updateIsLoadingLastPrice,
  updateSymbolType,
  loadLastPrice,
  loadBalance,
} from './symbols/SymbolActions'

import {
  updateEmojis,
  updateSelectEmojiPopoverOpen,
} from './emojis/EmojiActions'

import {
  updateExchanges,
  updateIsExchangeLoading,
  updateExchangeType,
  updateExchangeUpdated,
  updateExchangeKey,
  loadExchanges,
  updateTotalExchanges,
  updateActiveExchange,
  updateIsException,
  initExchanges,
  getUserExchangesAfterFBInit,
} from './exchanges/ExchangeActions'

import {
  updateIsOrderPlaced,
  updateIsOrderCancelled,
  updateOpenOrdersUC,
  updateDelOpenOrders,
  updateOrderEdited,
} from './orders/OrderActions'

import {
  updateDisableOrderHistoryRefreshBtn,
  updateDisableOpenOrdesrRefreshBtn,
  updateDisablePortfolioRefreshBtn,
  updateDisableAnalyticsRefreshBtn,
  updateRefreshButton,
  refreshExchanges,
} from './refresh/RefreshActions'

import {
  updateTemplateDrawings,
  updateTemplateDrawingsOpen,
} from './templates/TemplateActions'

import {
  updateIsTradersModalOpen,
  updateActiveTrader,
  setActiveAnalysts,
} from './trades/TradeActions'

import {
  updateMarketData,
  updateShowMarketItems,
  updateWatchListOpen,
  initMarketData,
  updateProducts,
  getProducts,
} from './market/MarketActions'

import {
  updateLoadApiKeys,
  updateLoadApiKeysError,
  updateIsApiKeysLoading,
} from './apiKeys/ApiKeysActions'

import {
  updateUserData,
  updateUserState,
  updateUserContextLoaded,
  updateAllAnalysts,
  updateIsAnalyst,
  fetchAnalysts,
  add2FA,
  verify2FA,
  delete2FA,
  login,
  logout,
  register,
  handleFirstLogin,
  updateCanaryUser,
} from './users/UsersActions'

import {
  updateIsOnboardingSkipped,
  updateRememberCheck,
  updateLoaderVisible,
  updateOnTour,
  updateIsTourStep5,
  updateIsTourFinished,
  updateOnSecondTour,
  updateTour2CurrentStep,
  updateTwofaSecretKey,
  updateCountry,
  updateIsCountryAvailable,
  updateEndTrial,
  updateNeedPayment,
  updateShowSubModal,
  handleOnboardingSkip,
  handleOnboardingShow,
  sendEmailAgain,
  handleCountry,
  findFastServer,
} from './appFlow/AppFlowActions'

import {
  updateIsCheckingSub,
  updateHasSub,
  updateSubscriptionData,
  updateTrialDaysLeft,
  updateIsPaidUser,
  updateCreateSubscription,
  updateSubscriptionError,
  updateSubscriptionsDetails,
} from './subscription/SubscriptionActions'

import {
  updateChartData,
  updateChartMirroring,
  updateIsChartReady,
  updateActiveDrawingId,
  updateActiveDrawing,
  updateAddedDrawing,
  updateChartDrawings,
  updateSettingChartDrawings,
  getChartMirroring,
  updateChartDataOnInit,
  updateSunburstChart,
} from './charts/ChartActions'

import {
  updatePairOperations,
  updatePairPerformance,
  updateAssetPerformance,
  updateAnalyticsLoading,
  updateLoadingError,
  refreshAnalyticsData,
} from './analytics/AnalyticsActions'

import {
  updateTickers,
  updateLastMessage,
  updateEstimate,
  updateBalance,
  updatePortfolioLoading,
  updateElapsed,
  updatePortMarketData,
  updateSelectedExchanges,
  refreshPortfolioData,
} from './portfolio/PortfolioActions'

import {
  addEntry,
  addMarketEntry,
  addEntryStopLimit,
  addEntryStopMarket,
  addTarget,
  addStopMarketTarget,
  addStoplossLimit,
  addStoplossMarket,
  resetTradeState,
  resetStoploss,
  resetTarget,
} from './simpleTrade/SimpleTradeActions'

export {
  updateSymbols,
  updateSymbolDetails,
  updateSelectedSymbol,
  updateSelectedSymbolDetail,
  updateSelectedSymbolBalance,
  updateSelectedBaseSymbolBalance,
  updateIsLoadingBalance,
  updateSelectedSymbolLastPrice,
  updateIsLoadingLastPrice,
  updateSymbolType,
  loadLastPrice,
  loadBalance,
  updateEmojis,
  updateSelectEmojiPopoverOpen,
  updateExchanges,
  updateIsExchangeLoading,
  updateExchangeType,
  updateExchangeUpdated,
  updateExchangeKey,
  loadExchanges,
  updateTotalExchanges,
  updateActiveExchange,
  updateIsException,
  initExchanges,
  getUserExchangesAfterFBInit,
  updateIsOrderPlaced,
  updateIsOrderCancelled,
  updateOpenOrdersUC,
  updateDelOpenOrders,
  updateOrderEdited,
  updateDisableOrderHistoryRefreshBtn,
  updateDisableOpenOrdesrRefreshBtn,
  updateDisablePortfolioRefreshBtn,
  updateDisableAnalyticsRefreshBtn,
  updateRefreshButton,
  refreshExchanges,
  updateTemplateDrawings,
  updateTemplateDrawingsOpen,
  updateIsTradersModalOpen,
  updateActiveTrader,
  setActiveAnalysts,
  updateMarketData,
  updateShowMarketItems,
  updateWatchListOpen,
  initMarketData,
  updateProducts,
  getProducts,
  updateLoadApiKeys,
  updateLoadApiKeysError,
  updateIsApiKeysLoading,
  updateUserData,
  updateUserState,
  updateUserContextLoaded,
  updateAllAnalysts,
  updateIsAnalyst,
  fetchAnalysts,
  handleFirstLogin,
  updateCanaryUser,
  add2FA,
  verify2FA,
  delete2FA,
  login,
  logout,
  register,
  updateIsOnboardingSkipped,
  updateRememberCheck,
  updateLoaderVisible,
  updateOnTour,
  updateIsTourStep5,
  updateIsTourFinished,
  updateOnSecondTour,
  updateTour2CurrentStep,
  updateTwofaSecretKey,
  updateCountry,
  updateIsCountryAvailable,
  updateEndTrial,
  updateNeedPayment,
  updateShowSubModal,
  handleOnboardingSkip,
  handleOnboardingShow,
  sendEmailAgain,
  handleCountry,
  findFastServer,
  updateIsCheckingSub,
  updateHasSub,
  updateSubscriptionData,
  updateTrialDaysLeft,
  updateIsPaidUser,
  updateCreateSubscription,
  updateSubscriptionError,
  updateSubscriptionsDetails,
  updateChartData,
  updateChartMirroring,
  updateIsChartReady,
  updateActiveDrawingId,
  updateActiveDrawing,
  updateAddedDrawing,
  updateChartDrawings,
  updateSettingChartDrawings,
  getChartMirroring,
  updateChartDataOnInit,
  updateSunburstChart,
  updatePairOperations,
  updatePairPerformance,
  updateAssetPerformance,
  updateAnalyticsLoading,
  updateLoadingError,
  refreshAnalyticsData,
  updateTickers,
  updateLastMessage,
  updateEstimate,
  updateBalance,
  updatePortfolioLoading,
  updateElapsed,
  updatePortMarketData,
  updateSelectedExchanges,
  refreshPortfolioData,
  addEntry,
  addMarketEntry,
  addEntryStopLimit,
  addEntryStopMarket,
  addTarget,
  addStopMarketTarget,
  addStoplossLimit,
  addStoplossMarket,
  resetTradeState,
  resetStoploss,
  resetTarget,
}
